name: Kubernetes CI/CD

on:
  push:
    branches: [ main ]

env:
  IMAGE: txjas99/flask-k8s-app

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - run: pytest

  build-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push
      run: |
        docker build -t $IMAGE:${{ github.sha }} .
        docker push $IMAGE:${{ github.sha }}
